version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notes_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes_network

volumes:
  postgres_data:

networks:
  notes_network:
